/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller

object App {
  def main(args: Array[String]): Unit = {
    val hanoi = new Torre_hanoi
    hanoi.listaTorresHanoi(5,'A','C','B')
  }

  def greeting(): String = "Hello, world!"
}
